#! /bin/sh
rm -rf 3518E-SOFTWARE.bin
dd if=$1 of=3518E-SOFTWARE.bin bs=1k conv=sync
dd if=$2 of=3518E-SOFTWARE.bin bs=1k seek=512
dd if=$3 of=3518E-SOFTWARE.bin bs=1k seek=2560
dd if=$4 of=3518E-SOFTWARE.bin bs=1k seek=4608 
dd if=$5 of=3518E-SOFTWARE.bin bs=1k seek=7680 conv=sync
#0.5  2   2  3  0.5
