##############################################################
#
# Copyright (C), ZMODO Technology Corp., Ltd.
#
# File Name : Makefile
#
# Author : hayson <haysonzeng@zmodo.cn>
#
# Create Date : 2014-1-22
#
##############################################################



OBJECTS_DIR=./objects
DEPFILE=./deps
OUT_PUT=./output

all:3518


3518:
	@make -j99 -f Makefile.3518 

.PHONY:clean

clean:
	rm -rf $(DEPFILE)
	rm -rf $(OBJECTS_DIR)/*.o
	rm -rf $(OUT_PUT)/*

	
